### ISSUE TITLE
Alter the compose file so that watchtower is scoped to update only the containers in the stack

### ISSUE THREAD

**Issue by maxiride** [ArchiveBox/good-karma-kit#1]
From my understanding, as of now, watchtower will monitor and update all the containers on the host which might be unwanted.

From [the watchtower docs](https://containrrr.dev/watchtower/running-multiple-instances/) it can be scoped and can live happily with other watchtower instances as long as it is scoped.

I'd suggest to add a scope to all the containers:

        labels:
          - "com.centurylinklabs.watchtower.scope=good-karma-kit"

**Comment by pirate** [comment]
Yeah, I was hoping for this: https://github.com/containrrr/watchtower/issues/895 but it looks like it's not going to be a quick fix, so I'll add the labels.

**Comment by pirate** [comment]
https://github.com/ArchiveBox/good-karma-kit/commit/27822881b5c08f48124eac57257622cb8d4e68c2
